version: "3.3"

services:
  backend:
    image: warehouse-devops
    hostname: warehouse
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "6500:6500"
    container_name: warehouse
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/warehouse
      SPRING_DATASOURCE_USERNAME: hackerearth
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 6500
      
  database:
    image: postgres
    restart: on-failure
    hostname: database
    expose:
      - 5432
    container_name: database
    ports:
      - "5432:5432"
    environment:
      HOSTNAME: database
      POSTGRES_USER: hackerearth
      POSTGRES_PASSWORD: devops123
      PGUSER: hackerearth
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./dbfiles/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "database", "-p", "5432", "-d", "warehouse", "-U", "hackerearth"]
      interval: 10s
 
volumes:
  dbfiles: