version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/warehouse
      - SPRING_DATASOURCE_USERNAME=hackerearth
      - SPRING_DATASOURCE_PASSWORD=devops123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_HIBERNATE_SHOW_SQL=true
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=hackerearth
      - POSTGRES_PASSWORD=devops123