version: '3.8'

services:
  backend:
    image: warehouse-devops
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    networks:
      - warehouse-networks
    ports:
      - "6500:6500"
    container_name: warehouse
    depends_on:
      - database
    links:
      - database:database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/warehouse
      SPRING_DATASOURCE_USERNAME: hackerearth
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 6500
      
  database:
    image: postgres
    restart: always
    expose:
      - 5432
    container_name: database
    networks:
      - warehouse-networks
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hackerearth
      POSTGRES_PASSWORD: devops123
      PGDATA: /data/prostgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./dbfiles/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432", "-d", "warehouse", "-U", "hackerearth"]
      interval: 10s
 
networks:
  warehouse-networks:
    driver: bridge