version: '3.8'

services:
  backend:
    image: warehouse-devops
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: ./.env
    networks:
      - warehouse-networks
    ports:
      - "6500:6500"
    container_name: warehouse
    depends_on:
      - database
    links:
      - database:database
    environment:
      SPRING_APPLICATION_JSON
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/warehouse
      SPRING_DATASOURCE_USERNAME: hackerearth
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 6500
      
  database:
    image: postgres
    restart: on-failure
    expose:
      - 5432
    container_name: database
    networks:
      - warehouse-networks
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hackerearth
      POSTGRES_PASSWORD: devops123
      PGUSER: hackerearth
      PGDATA: /data/postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./dbfiles/:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "database", "-p", "5432", "-d", "warehouse", "-U", "hackerearth"]
      interval: 10s
 
networks:
  warehouse-networks:
    driver: bridge

volumes:
  dbfiles: