services:
  backend:
    build: .
    restart: always
    networks:
      - warehouse-networks
    ports:
      - "6500:8080"
    container_name: warehouse
    depends_on:
      - database
    links:
      - database:database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/warehouse
      SPRING_DATASOURCE_USERNAME: hackerearth
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_SHOW_SQL: true
      SERVER_PORT: 6500
      
  database:
    image: 'postgres:latest'
    restart: always
    container_name: database
    networks:
      - warehouse-networks
    ports:
      - "5432:5432"
    volumes:
      - ./dbfiles/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: hackerearth
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: warehouse
  
networks:
  warehouse-networks:
    driver: bridge